#!/usr/bin/env python3
"""Generate task-level RGB/depth frame ranges from IMU-derived task times."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
from typing import Iterable

import h5py
import numpy as np
import pandas as pd

try:
    from tqdm.auto import tqdm
except ImportError:  # pragma: no cover - tqdm is available in the imagebind env.
    tqdm = None


NON_STRESS_TASKS = frozenset({"jelly", "count", "baseline"})
STRESS_TASKS = frozenset({"bad", "stress", "arithmetic", "stroop"})
TARGET_TASKS = NON_STRESS_TASKS | STRESS_TASKS
TIMESTAMP_DATASET_CANDIDATES = ("timestamps", "timestamp", "time", "times", "frame_timestamps")
VERSION_SUFFIX_RE = re.compile(r"v\d+$")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Use IMU task labels as coarse task start/end anchors and map those intervals "
            "onto RGB/depth H5 timestamp arrays."
        )
    )
    parser.add_argument(
        "--session-manifest",
        default="assets/imu_video_mapping/imu_to_video_session_manifest.csv",
        help="Session-level IMU-to-video manifest generated by generate_imu_video_mapping_manifest.py.",
    )
    parser.add_argument(
        "--output-csv",
        default="assets/imu_video_mapping/rgb_depth_task_frame_manifest.csv",
        help="Output task/frame manifest CSV.",
    )
    parser.add_argument("--raw-sample-rate-hz", type=float, default=32.0)
    parser.add_argument("--timestamp-dataset", default=None, help="Optional explicit H5 timestamp dataset name.")
    parser.add_argument(
        "--coverage-tolerance-seconds",
        type=float,
        default=0.25,
        help="Allowed start/end timestamp shortfall before a task is marked partial instead of complete.",
    )
    parser.add_argument("--participants", nargs="*", default=None, help="Optional IMU stems to process.")
    parser.add_argument("--tasks", nargs="*", default=None, help="Optional target task ids to process.")
    parser.add_argument("--max-session-rows", type=int, default=None, help="Optional smoke-test row limit.")
    parser.add_argument(
        "--skip-h5",
        action="store_true",
        help="Emit IMU-derived task intervals without opening RGB/depth H5 files.",
    )
    parser.add_argument("--no-progress", action="store_true", help="Disable tqdm progress bars.")
    return parser.parse_args()


def canonical_subject_id(subject_id: str) -> str:
    return VERSION_SUFFIX_RE.sub("", str(subject_id))


def task_to_label(task_id: str) -> int:
    if task_id in NON_STRESS_TASKS:
        return 0
    if task_id in STRESS_TASKS:
        return 1
    raise ValueError(f"Unsupported task label: {task_id}")


def find_h5_dataset(h5_file: h5py.File, explicit_name: str | None, candidates: Iterable[str]) -> str:
    if explicit_name:
        if explicit_name not in h5_file:
            raise KeyError(f"Requested dataset '{explicit_name}' not found in {h5_file.filename}")
        return explicit_name
    for name in candidates:
        if name in h5_file:
            return name
    available = []
    h5_file.visititems(lambda name, obj: available.append(name) if isinstance(obj, h5py.Dataset) else None)
    raise KeyError(
        f"No timestamp dataset found in {h5_file.filename}. "
        f"Tried {list(candidates)}. Available datasets: {available[:20]}"
    )


def normalize_timestamp_units(timestamps: np.ndarray) -> tuple[np.ndarray, str]:
    """Return timestamps in epoch seconds.

    The IMU CSVs use epoch seconds, while the RGB/depth H5 files observed so far
    store epoch milliseconds.
    """
    timestamps = np.asarray(timestamps, dtype=np.float64)
    finite = timestamps[np.isfinite(timestamps)]
    if finite.size == 0:
        return timestamps, "unknown"
    median_abs = float(np.median(np.abs(finite)))
    if median_abs > 1e11:
        return timestamps / 1000.0, "milliseconds"
    return timestamps, "seconds"


def read_timestamps(path: Path, timestamp_dataset: str | None) -> tuple[np.ndarray | None, str | None, str | None]:
    try:
        with h5py.File(path, "r") as h5_file:
            dataset_name = find_h5_dataset(h5_file, timestamp_dataset, TIMESTAMP_DATASET_CANDIDATES)
            timestamps = np.asarray(h5_file[dataset_name][:], dtype=np.float64)
        timestamps, timestamp_units = normalize_timestamp_units(timestamps)
        timestamps = timestamps[np.isfinite(timestamps)]
        if timestamps.size == 0:
            return None, dataset_name, "timestamp_dataset_empty"
        return timestamps, f"{dataset_name}|{timestamp_units}", None
    except Exception as exc:  # noqa: BLE001 - this is an inspection/reporting script.
        return None, None, f"{type(exc).__name__}: {exc}"


def build_imu_task_segments(imu_csv_path: Path, raw_sample_rate_hz: float) -> pd.DataFrame:
    df = pd.read_csv(imu_csv_path, usecols=["time", "label"])
    if df.empty:
        return pd.DataFrame()
    first_time = float(pd.to_numeric(df["time"], errors="coerce").dropna().iloc[0])
    labels = df["label"].fillna("").astype(str).to_numpy()
    sample_times = first_time + (np.arange(len(df), dtype=np.float64) / float(raw_sample_rate_hz))
    rows: list[dict] = []
    segment_start: int | None = None
    current_task: str | None = None
    task_ordinal: dict[str, int] = {}

    def close_segment(end_index: int) -> None:
        nonlocal segment_start, current_task
        if segment_start is None or current_task is None:
            return
        task_ordinal[current_task] = task_ordinal.get(current_task, 0) + 1
        start_time = float(sample_times[segment_start])
        end_time = float(sample_times[end_index - 1] + (1.0 / float(raw_sample_rate_hz)))
        rows.append(
            {
                "task_id": current_task,
                "task_segment_ordinal": task_ordinal[current_task],
                "stress_label": task_to_label(current_task),
                "imu_task_start_ts": start_time,
                "imu_task_end_ts": end_time,
                "imu_task_duration_seconds": end_time - start_time,
                "imu_start_row": int(segment_start),
                "imu_end_row_exclusive": int(end_index),
                "imu_num_rows": int(end_index - segment_start),
            }
        )
        segment_start = None
        current_task = None

    for index, raw_label in enumerate(labels):
        task_id = raw_label if raw_label in TARGET_TASKS else None
        if task_id is None:
            close_segment(index)
            continue
        if segment_start is None:
            segment_start = index
            current_task = task_id
            continue
        if task_id != current_task:
            close_segment(index)
            segment_start = index
            current_task = task_id

    close_segment(len(labels))
    return pd.DataFrame(rows)


def frame_range_for_interval(
    timestamps: np.ndarray | None,
    start_ts: float,
    end_ts: float,
    tolerance_seconds: float,
) -> dict:
    if timestamps is None or timestamps.size == 0:
        return {
            "has_overlap": False,
            "coverage_status": "missing",
            "start_frame_index": pd.NA,
            "end_frame_index_exclusive": pd.NA,
            "start_frame_ts": pd.NA,
            "end_frame_ts": pd.NA,
            "coverage_duration_seconds": 0.0,
            "num_frames": 0,
        }

    start_index = int(np.searchsorted(timestamps, start_ts, side="left"))
    end_index_exclusive = int(np.searchsorted(timestamps, end_ts, side="right"))
    if start_index >= end_index_exclusive:
        return {
            "has_overlap": False,
            "coverage_status": "missing",
            "start_frame_index": pd.NA,
            "end_frame_index_exclusive": pd.NA,
            "start_frame_ts": pd.NA,
            "end_frame_ts": pd.NA,
            "coverage_duration_seconds": 0.0,
            "num_frames": 0,
        }

    first_ts = float(timestamps[start_index])
    last_ts = float(timestamps[end_index_exclusive - 1])
    start_ok = first_ts <= (start_ts + tolerance_seconds)
    end_ok = last_ts >= (end_ts - tolerance_seconds)
    status = "complete" if start_ok and end_ok else "partial"
    return {
        "has_overlap": True,
        "coverage_status": status,
        "start_frame_index": start_index,
        "end_frame_index_exclusive": end_index_exclusive,
        "start_frame_ts": first_ts,
        "end_frame_ts": last_ts,
        "coverage_duration_seconds": max(0.0, last_ts - first_ts),
        "num_frames": int(end_index_exclusive - start_index),
    }


def prefix_keys(prefix: str, payload: dict) -> dict:
    return {f"{prefix}_{key}": value for key, value in payload.items()}


def progress_iter(iterable, **kwargs):
    if tqdm is None:
        return iterable
    return tqdm(iterable, **kwargs)


def main() -> None:
    args = parse_args()
    session_manifest_path = Path(args.session_manifest).resolve()
    output_csv = Path(args.output_csv).resolve()
    output_csv.parent.mkdir(parents=True, exist_ok=True)

    session_df = pd.read_csv(session_manifest_path)
    if args.participants:
        participants = {str(item) for item in args.participants}
        session_df = session_df[session_df["imu_stem"].astype(str).isin(participants)].copy()
    if args.max_session_rows is not None:
        session_df = session_df.head(int(args.max_session_rows)).copy()

    requested_tasks = set(args.tasks or TARGET_TASKS)
    invalid_tasks = requested_tasks - TARGET_TASKS
    if invalid_tasks:
        raise ValueError(f"Unsupported task ids requested: {sorted(invalid_tasks)}")

    imu_segment_cache: dict[str, pd.DataFrame] = {}
    timestamp_cache: dict[tuple[str, str], tuple[np.ndarray | None, str | None, str | None]] = {}
    rows: list[dict] = []
    session_records = list(session_df.reset_index(drop=True).iterrows())
    iterator = session_records
    if not args.no_progress:
        iterator = progress_iter(session_records, desc="Mapping sessions to task frame ranges", unit="session")

    for session_index, session_row in iterator:
        imu_csv_path = Path(str(session_row["imu_csv_path"]))
        cache_key = str(imu_csv_path)
        if cache_key not in imu_segment_cache:
            imu_segment_cache[cache_key] = build_imu_task_segments(imu_csv_path, args.raw_sample_rate_hz)
        task_segments = imu_segment_cache[cache_key]
        if task_segments.empty:
            continue
        task_segments = task_segments[task_segments["task_id"].isin(requested_tasks)].copy()

        modality_timestamps = {}
        for modality in ("depth", "rgb"):
            path = Path(str(session_row[f"{modality}_path"]))
            ts_key = (modality, str(path))
            if args.skip_h5:
                timestamp_cache[ts_key] = (None, "", "skipped_h5_timestamp_inspection")
            elif ts_key not in timestamp_cache:
                timestamp_cache[ts_key] = read_timestamps(path, args.timestamp_dataset)
            modality_timestamps[modality] = timestamp_cache[ts_key]

        for segment in task_segments.itertuples(index=False):
            task_record_id = (
                f"{session_row['group']}__{session_row['imu_stem']}__{session_row['view_type']}__"
                f"{segment.task_id}__{int(segment.task_segment_ordinal):02d}"
            )
            payload = {
                "task_record_id": task_record_id,
                "session_manifest_row": int(session_index),
                "group": session_row["group"],
                "manifest_group": session_row.get("manifest_group", ""),
                "imu_stem": session_row["imu_stem"],
                "base_subject_id": canonical_subject_id(session_row["imu_stem"]),
                "participant_id": session_row["participant_id"],
                "participant_id_norm": session_row["participant_id_norm"],
                "global_time_id": session_row["global_time_id"],
                "view_type": session_row.get("view_type", ""),
                "imu_csv_path": session_row["imu_csv_path"],
                "depth_path": session_row["depth_path"],
                "rgb_path": session_row["rgb_path"],
                "depth_filename": session_row["depth_filename"],
                "rgb_filename": session_row["rgb_filename"],
                "task_id": segment.task_id,
                "task_segment_ordinal": int(segment.task_segment_ordinal),
                "stress_label": int(segment.stress_label),
                "imu_task_start_ts": float(segment.imu_task_start_ts),
                "imu_task_end_ts": float(segment.imu_task_end_ts),
                "imu_task_duration_seconds": float(segment.imu_task_duration_seconds),
                "imu_start_row": int(segment.imu_start_row),
                "imu_end_row_exclusive": int(segment.imu_end_row_exclusive),
                "imu_num_rows": int(segment.imu_num_rows),
            }

            coverage_statuses = []
            for modality, (timestamps, dataset_name, error) in modality_timestamps.items():
                frame_payload = frame_range_for_interval(
                    timestamps,
                    float(segment.imu_task_start_ts),
                    float(segment.imu_task_end_ts),
                    float(args.coverage_tolerance_seconds),
                )
                frame_payload["timestamp_dataset"] = dataset_name or ""
                frame_payload["timestamp_error"] = error or ""
                if error == "skipped_h5_timestamp_inspection":
                    frame_payload["coverage_status"] = "not_inspected"
                elif error:
                    frame_payload["coverage_status"] = "error"
                coverage_statuses.append(frame_payload["coverage_status"])
                payload.update(prefix_keys(modality, frame_payload))

            if "error" in coverage_statuses:
                combined_status = "error"
            elif "not_inspected" in coverage_statuses:
                combined_status = "not_inspected"
            elif "missing" in coverage_statuses:
                combined_status = "missing"
            elif "partial" in coverage_statuses:
                combined_status = "partial"
            else:
                combined_status = "complete"
            payload["combined_coverage_status"] = combined_status
            payload["both_modalities_have_overlap"] = bool(
                payload["depth_has_overlap"] and payload["rgb_has_overlap"]
            )
            rows.append(payload)

    output_df = pd.DataFrame(rows)
    output_df.to_csv(output_csv, index=False)
    print(f"Wrote task/frame manifest to {output_csv}")
    print(f"Rows: {len(output_df)}")
    if not output_df.empty:
        print(output_df["combined_coverage_status"].value_counts(dropna=False).to_string())


if __name__ == "__main__":
    main()
