#!/usr/bin/env python3
"""Write 5 Hz task-aligned RGB/depth Zarr stores from a task/frame manifest."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re
from typing import Iterable

import h5py
import numpy as np
import pandas as pd

try:
    import cv2
except ImportError:  # pragma: no cover - cv2 is available in the imagebind env.
    cv2 = None

try:
    from tqdm.auto import tqdm
except ImportError:  # pragma: no cover - tqdm is available in the imagebind env.
    tqdm = None


IMAGE_DATASET_CANDIDATES = ("images", "frames", "rgb", "depth")
TIMESTAMP_DATASET_CANDIDATES = ("timestamps", "timestamp", "time", "times", "frame_timestamps")
SAFE_NAME_RE = re.compile(r"[^A-Za-z0-9_.-]+")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Downsample task-aligned RGB/depth H5 intervals to 5 Hz and save raw, "
            "unmasked participant-wise Zarr stores."
        )
    )
    parser.add_argument(
        "--task-frame-manifest",
        default="assets/imu_video_mapping/rgb_depth_task_frame_manifest.csv",
        help="Task/frame manifest generated by generate_rgb_depth_task_frame_manifest.py.",
    )
    parser.add_argument("--output-root", required=True, help="Directory where participant-wise Zarr stores are written.")
    parser.add_argument("--sample-rate-hz", type=float, default=5.0)
    parser.add_argument("--nearest-tolerance-seconds", type=float, default=0.25)
    parser.add_argument("--image-dataset", default=None, help="Optional explicit H5 image dataset name.")
    parser.add_argument("--timestamp-dataset", default=None, help="Optional explicit H5 timestamp dataset name.")
    parser.add_argument("--resize-height", type=int, default=224)
    parser.add_argument("--resize-width", type=int, default=224)
    parser.add_argument("--no-resize", action="store_true", help="Keep source frame resolution.")
    parser.add_argument("--frames-per-chunk", type=int, default=150, help="Default chunk is 30 seconds at 5 Hz.")
    parser.add_argument("--compressor", default="zstd", choices=["zstd", "lz4", "blosclz", "zlib"])
    parser.add_argument("--compression-level", type=int, default=5)
    parser.add_argument("--participants", nargs="*", default=None, help="Optional IMU stems/base ids to process.")
    parser.add_argument("--tasks", nargs="*", default=None, help="Optional task ids to process.")
    parser.add_argument("--views", nargs="*", default=None, help="Optional view types to process, e.g. frontal side.")
    parser.add_argument("--max-rows", type=int, default=None, help="Optional smoke-test row limit.")
    parser.add_argument("--num-shards", type=int, default=1, help="Split manifest rows into this many shards.")
    parser.add_argument("--shard-index", type=int, default=0, help="Zero-based shard index to process.")
    parser.add_argument(
        "--shard-by",
        choices=["subject", "row"],
        default="subject",
        help="Shard by base_subject_id by default so parallel jobs do not write the same participant Zarr store.",
    )
    parser.add_argument("--require-complete", action="store_true", help="Skip partial-coverage task rows.")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing task groups inside Zarr stores.")
    parser.add_argument("--no-progress", action="store_true", help="Disable tqdm progress bars.")
    return parser.parse_args()


def require_zarr_modules():
    try:
        import zarr
        from numcodecs import Blosc
    except ImportError as exc:  # pragma: no cover - environment-dependent.
        raise SystemExit(
            "This script requires zarr and numcodecs. In this project, run it inside the "
            "imagebind conda env or install them with: pip install zarr numcodecs"
        ) from exc
    return zarr, Blosc


def safe_name(value: object) -> str:
    text = str(value)
    text = SAFE_NAME_RE.sub("_", text).strip("_")
    return text or "unknown"


def progress_iter(iterable, **kwargs):
    if tqdm is None:
        return iterable
    return tqdm(iterable, **kwargs)


def find_h5_dataset(h5_file: h5py.File, explicit_name: str | None, candidates: Iterable[str]) -> str:
    if explicit_name:
        if explicit_name not in h5_file:
            raise KeyError(f"Requested dataset '{explicit_name}' not found in {h5_file.filename}")
        return explicit_name
    for name in candidates:
        if name in h5_file:
            return name
    available = []
    h5_file.visititems(lambda name, obj: available.append(name) if isinstance(obj, h5py.Dataset) else None)
    raise KeyError(f"No matching dataset found in {h5_file.filename}. Available datasets: {available[:20]}")


def read_timestamps(h5_file: h5py.File, explicit_name: str | None) -> tuple[str, np.ndarray]:
    dataset_name = find_h5_dataset(h5_file, explicit_name, TIMESTAMP_DATASET_CANDIDATES)
    return dataset_name, np.asarray(h5_file[dataset_name][:], dtype=np.float64)


def nearest_indices(
    timestamps: np.ndarray,
    target_times: np.ndarray,
    start_index: int,
    end_index_exclusive: int,
    tolerance_seconds: float,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    if timestamps.size == 0 or target_times.size == 0:
        empty_i = np.asarray([], dtype=np.int64)
        empty_f = np.asarray([], dtype=np.float64)
        return empty_i, empty_f, empty_f

    positions = np.searchsorted(timestamps, target_times, side="left")
    right = np.clip(positions, 0, len(timestamps) - 1)
    left = np.clip(positions - 1, 0, len(timestamps) - 1)
    choose_right = np.abs(timestamps[right] - target_times) < np.abs(timestamps[left] - target_times)
    indices = np.where(choose_right, right, left).astype(np.int64)
    source_times = timestamps[indices]
    gaps = np.abs(source_times - target_times)
    valid = (
        (indices >= int(start_index))
        & (indices < int(end_index_exclusive))
        & np.isfinite(source_times)
        & (gaps <= float(tolerance_seconds))
    )
    return indices[valid], source_times[valid], target_times[valid]


def normalize_rgb_frame(frame: np.ndarray) -> np.ndarray:
    frame = np.asarray(frame)
    if frame.ndim == 3 and frame.shape[0] in (3, 4) and frame.shape[-1] not in (3, 4):
        frame = np.moveaxis(frame, 0, -1)
    if frame.ndim == 2:
        frame = np.repeat(frame[:, :, None], 3, axis=2)
    if frame.ndim == 3 and frame.shape[-1] > 3:
        frame = frame[:, :, :3]
    return frame


def normalize_depth_frame(frame: np.ndarray) -> np.ndarray:
    frame = np.asarray(frame)
    if frame.ndim == 3:
        frame = np.squeeze(frame)
    if frame.ndim != 2:
        raise ValueError(f"Expected a 2D depth frame after squeeze, got shape {frame.shape}")
    return frame


def resize_frame(frame: np.ndarray, resize_shape: tuple[int, int] | None, modality: str) -> np.ndarray:
    if resize_shape is None:
        return frame
    height, width = resize_shape
    if frame.shape[0] == height and frame.shape[1] == width:
        return frame
    if cv2 is None:
        row_idx = np.linspace(0, frame.shape[0] - 1, height).round().astype(np.int64)
        col_idx = np.linspace(0, frame.shape[1] - 1, width).round().astype(np.int64)
        return frame[row_idx][:, col_idx]

    interpolation = cv2.INTER_AREA if modality == "rgb" else cv2.INTER_NEAREST
    input_dtype = frame.dtype
    resize_input = frame.astype(np.float32) if input_dtype == np.float16 else frame
    resized = cv2.resize(resize_input, (width, height), interpolation=interpolation)
    if resized.dtype != input_dtype and np.issubdtype(input_dtype, np.floating):
        resized = resized.astype(input_dtype)
    return resized


def read_processed_frame(
    dataset: h5py.Dataset,
    frame_index: int,
    modality: str,
    resize_shape: tuple[int, int] | None,
) -> np.ndarray:
    frame = np.asarray(dataset[int(frame_index)])
    frame = normalize_rgb_frame(frame) if modality == "rgb" else normalize_depth_frame(frame)
    return resize_frame(frame, resize_shape, modality)


def write_frame_array(
    output_array,
    source_dataset: h5py.Dataset,
    frame_indices: np.ndarray,
    modality: str,
    resize_shape: tuple[int, int] | None,
    frames_per_chunk: int,
    output_offset: int = 0,
    progress=None,
) -> None:
    for start in range(0, len(frame_indices), frames_per_chunk):
        end = min(start + frames_per_chunk, len(frame_indices))
        frames = [
            read_processed_frame(source_dataset, int(frame_index), modality, resize_shape)
            for frame_index in frame_indices[start:end]
        ]
        output_array[output_offset + start : output_offset + end] = np.stack(frames, axis=0)
        if progress is not None:
            progress.update(end - start)


def create_dataset(group, name: str, data: np.ndarray, chunks, compressor) -> None:
    dataset = group.create_dataset(
        name,
        shape=data.shape,
        chunks=chunks,
        dtype=data.dtype,
        compressor=compressor,
        overwrite=True,
    )
    dataset[:] = data


def row_is_processable(row: pd.Series, require_complete: bool) -> bool:
    if not bool(row.get("both_modalities_have_overlap", False)):
        return False
    if require_complete and row.get("combined_coverage_status") != "complete":
        return False
    return row.get("combined_coverage_status") in {"complete", "partial"}


def stable_shard_id(value: object, num_shards: int) -> int:
    digest = hashlib.md5(str(value).encode("utf-8")).hexdigest()
    return int(digest[:12], 16) % int(num_shards)


def main() -> None:
    args = parse_args()
    zarr, Blosc = require_zarr_modules()
    task_frame_manifest = Path(args.task_frame_manifest).resolve()
    output_root = Path(args.output_root).resolve()
    output_root.mkdir(parents=True, exist_ok=True)

    manifest_df = pd.read_csv(task_frame_manifest)
    if args.participants:
        participants = {str(item) for item in args.participants}
        manifest_df = manifest_df[
            manifest_df["imu_stem"].astype(str).isin(participants)
            | manifest_df["base_subject_id"].astype(str).isin(participants)
        ].copy()
    if args.tasks:
        manifest_df = manifest_df[manifest_df["task_id"].astype(str).isin(set(args.tasks))].copy()
    if args.views:
        manifest_df = manifest_df[manifest_df["view_type"].astype(str).isin(set(args.views))].copy()
    if args.num_shards <= 0:
        raise ValueError("--num-shards must be positive")
    if args.shard_index < 0 or args.shard_index >= args.num_shards:
        raise ValueError("--shard-index must satisfy 0 <= shard_index < num_shards")
    if args.num_shards > 1:
        manifest_df = manifest_df.reset_index(drop=True)
        if args.shard_by == "row":
            shard_ids = manifest_df.index % int(args.num_shards)
        else:
            shard_ids = manifest_df["base_subject_id"].map(lambda value: stable_shard_id(value, args.num_shards))
        manifest_df = manifest_df[shard_ids == int(args.shard_index)].copy()
    if args.max_rows is not None:
        manifest_df = manifest_df.head(int(args.max_rows)).copy()

    resize_shape = None if args.no_resize else (int(args.resize_height), int(args.resize_width))
    compressor = Blosc(cname=args.compressor, clevel=int(args.compression_level), shuffle=Blosc.BITSHUFFLE)
    metadata_rows: list[dict] = []
    skipped_rows: list[dict] = []
    manifest_records = list(manifest_df.reset_index(drop=True).iterrows())
    iterator = manifest_records
    if not args.no_progress:
        iterator = progress_iter(manifest_records, desc="Writing task Zarr groups", unit="task")

    for row_index, row in iterator:
        if not row_is_processable(row, args.require_complete):
            skipped_rows.append(
                {
                    "task_record_id": row.get("task_record_id", ""),
                    "skip_reason": f"coverage_status={row.get('combined_coverage_status')}",
                }
            )
            continue

        depth_path = Path(str(row["depth_path"]))
        rgb_path = Path(str(row["rgb_path"]))
        try:
            with h5py.File(depth_path, "r") as depth_h5, h5py.File(rgb_path, "r") as rgb_h5:
                depth_image_name = find_h5_dataset(depth_h5, args.image_dataset, IMAGE_DATASET_CANDIDATES)
                rgb_image_name = find_h5_dataset(rgb_h5, args.image_dataset, IMAGE_DATASET_CANDIDATES)
                depth_ts_name, depth_timestamps = read_timestamps(depth_h5, args.timestamp_dataset)
                rgb_ts_name, rgb_timestamps = read_timestamps(rgb_h5, args.timestamp_dataset)

                target_times = np.arange(
                    float(row["imu_task_start_ts"]),
                    float(row["imu_task_end_ts"]),
                    1.0 / float(args.sample_rate_hz),
                    dtype=np.float64,
                )
                depth_indices, depth_source_ts, depth_target_ts = nearest_indices(
                    depth_timestamps,
                    target_times,
                    int(row["depth_start_frame_index"]),
                    int(row["depth_end_frame_index_exclusive"]),
                    float(args.nearest_tolerance_seconds),
                )
                rgb_indices, rgb_source_ts, rgb_target_ts = nearest_indices(
                    rgb_timestamps,
                    target_times,
                    int(row["rgb_start_frame_index"]),
                    int(row["rgb_end_frame_index_exclusive"]),
                    float(args.nearest_tolerance_seconds),
                )
                common_target_ts, depth_positions, rgb_positions = np.intersect1d(
                    depth_target_ts,
                    rgb_target_ts,
                    assume_unique=False,
                    return_indices=True,
                )
                if common_target_ts.size == 0:
                    skipped_rows.append(
                        {
                            "task_record_id": row.get("task_record_id", ""),
                            "skip_reason": "no_common_5hz_rgb_depth_samples",
                        }
                    )
                    continue

                depth_indices = depth_indices[depth_positions]
                depth_source_ts = depth_source_ts[depth_positions]
                rgb_indices = rgb_indices[rgb_positions]
                rgb_source_ts = rgb_source_ts[rgb_positions]

                depth_dataset = depth_h5[depth_image_name]
                rgb_dataset = rgb_h5[rgb_image_name]
                first_depth = read_processed_frame(depth_dataset, int(depth_indices[0]), "depth", resize_shape)
                first_rgb = read_processed_frame(rgb_dataset, int(rgb_indices[0]), "rgb", resize_shape)

                store_path = output_root / safe_name(row["group"]) / f"{safe_name(row['base_subject_id'])}.zarr"
                root = zarr.open_group(str(store_path), mode="a")
                root.attrs.update(
                    {
                        "group": str(row["group"]),
                        "base_subject_id": str(row["base_subject_id"]),
                        "sample_rate_hz": float(args.sample_rate_hz),
                        "resize_height": None if resize_shape is None else resize_shape[0],
                        "resize_width": None if resize_shape is None else resize_shape[1],
                        "preprocessing_stage": "raw_rgb_depth_5hz_task_streams",
                    }
                )
                tasks_group = root.require_group("tasks")
                task_group_name = safe_name(row["task_record_id"])
                if task_group_name in tasks_group:
                    if not args.overwrite:
                        skipped_rows.append(
                            {
                                "task_record_id": row.get("task_record_id", ""),
                                "skip_reason": "task_group_exists_use_overwrite",
                            }
                        )
                        continue
                    del tasks_group[task_group_name]
                task_group = tasks_group.create_group(task_group_name)
                task_group.attrs.update({key: str(value) for key, value in row.to_dict().items()})
                task_group.attrs.update(
                    {
                        "num_samples_5hz": int(common_target_ts.size),
                        "depth_image_dataset": depth_image_name,
                        "rgb_image_dataset": rgb_image_name,
                        "depth_timestamp_dataset": depth_ts_name,
                        "rgb_timestamp_dataset": rgb_ts_name,
                    }
                )

                n_samples = int(common_target_ts.size)
                chunk_n = max(1, min(int(args.frames_per_chunk), n_samples))
                rgb_array = task_group.create_dataset(
                    "rgb",
                    shape=(n_samples, *first_rgb.shape),
                    chunks=(chunk_n, *first_rgb.shape),
                    dtype=first_rgb.dtype,
                    compressor=compressor,
                    overwrite=True,
                )
                depth_array = task_group.create_dataset(
                    "depth",
                    shape=(n_samples, *first_depth.shape),
                    chunks=(chunk_n, *first_depth.shape),
                    dtype=first_depth.dtype,
                    compressor=compressor,
                    overwrite=True,
                )
                rgb_array[0] = first_rgb
                depth_array[0] = first_depth
                frame_progress = None
                if tqdm is not None and not args.no_progress:
                    frame_progress = tqdm(
                        total=max(0, (2 * n_samples) - 2),
                        desc=f"{row['task_record_id']} frames",
                        unit="frame",
                        leave=False,
                    )
                if n_samples > 1:
                    write_frame_array(
                        rgb_array,
                        rgb_dataset,
                        rgb_indices[1:],
                        "rgb",
                        resize_shape,
                        int(args.frames_per_chunk),
                        output_offset=1,
                        progress=frame_progress,
                    )
                    write_frame_array(
                        depth_array,
                        depth_dataset,
                        depth_indices[1:],
                        "depth",
                        resize_shape,
                        int(args.frames_per_chunk),
                        output_offset=1,
                        progress=frame_progress,
                    )
                if frame_progress is not None:
                    frame_progress.close()

                create_dataset(task_group, "target_timestamps", common_target_ts, chunks=(chunk_n,), compressor=compressor)
                create_dataset(task_group, "rgb_source_timestamps", rgb_source_ts, chunks=(chunk_n,), compressor=compressor)
                create_dataset(task_group, "depth_source_timestamps", depth_source_ts, chunks=(chunk_n,), compressor=compressor)
                create_dataset(task_group, "rgb_frame_indices", rgb_indices, chunks=(chunk_n,), compressor=compressor)
                create_dataset(task_group, "depth_frame_indices", depth_indices, chunks=(chunk_n,), compressor=compressor)

                metadata_rows.append(
                    {
                        "task_record_id": row["task_record_id"],
                        "zarr_path": str(store_path),
                        "zarr_task_group": f"tasks/{task_group_name}",
                        "group": row["group"],
                        "imu_stem": row["imu_stem"],
                        "base_subject_id": row["base_subject_id"],
                        "participant_id": row["participant_id"],
                        "view_type": row["view_type"],
                        "task_id": row["task_id"],
                        "stress_label": int(row["stress_label"]),
                        "num_samples_5hz": n_samples,
                        "sample_rate_hz": float(args.sample_rate_hz),
                        "rgb_shape": tuple(rgb_array.shape),
                        "depth_shape": tuple(depth_array.shape),
                    }
                )
                if tqdm is not None and not args.no_progress:
                    tqdm.write(
                        f"wrote {row['task_record_id']} -> {store_path} "
                        f"({n_samples} samples at {args.sample_rate_hz:g} Hz)"
                    )
        except Exception as exc:  # noqa: BLE001 - continue batch preprocessing and report failures.
            skipped_rows.append(
                {
                    "task_record_id": row.get("task_record_id", f"row_{row_index}"),
                    "skip_reason": f"{type(exc).__name__}: {exc}",
                }
            )

    metadata_path = output_root / "preprocessed_rgb_depth_metadata.csv"
    skipped_path = output_root / "preprocessed_rgb_depth_skipped.csv"
    pd.DataFrame(metadata_rows).to_csv(metadata_path, index=False)
    pd.DataFrame(skipped_rows).to_csv(skipped_path, index=False)
    print(f"Wrote metadata to {metadata_path}")
    print(f"Wrote skipped-row report to {skipped_path}")
    print(f"Processed task groups: {len(metadata_rows)}")
    print(f"Skipped rows: {len(skipped_rows)}")


if __name__ == "__main__":
    main()
